<a href="https://colab.research.google.com/github/AbdulNaeemB/Lab-Assignments/blob/main/Eigen_values_and_vectors_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import scipy.linalg as la

In [ ]:
A = np.array([[1,-1],[1,-2]])
result = la.eig(A)
print("Eigen values\n")
print(result[0])
print("Eigen vectors\n")
print(result[1])

Eigen values

[ 0.61803399+0.j -1.61803399+0.j]
Eigen vectors

[[0.93417236 0.35682209]
 [0.35682209 0.93417236]]


In [ ]:
eigen_values = result[0]
eigen_vectors = result[1]
print("Real eigen values")
print(eigen_values.real)

Real eigen values
[ 0.61803399 -1.61803399]


In [ ]:
eigvalues , eigvectors = la.eig(A)
print(eigvalues)
print(eigvectors)
print(eigvalues.real)

[ 0.61803399+0.j -1.61803399+0.j]
[[0.93417236 0.35682209]
 [0.35682209 0.93417236]]
[ 0.61803399 -1.61803399]


In [ ]:
lambda1 = eigvalues[1].real
v1 =  eigvectors[:,1].reshape(2,1)

In [ ]:
v1 * lambda1

array([[-0.57735027+0.j],
       [-1.51152263+0.j]])

In [ ]:
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[1 5 5 8]
 [6 2 9 1]
 [8 5 6 8]
 [3 8 7 4]]


In [ ]:
D = np.diag((3,1))
print(D)

[[3 0]
 [0 1]]


In [ ]:
S = P @ P.T
print(S)

[[115  69 127 110]
 [ 69 122 120 101]
 [127 120 189 138]
 [110 101 138 138]]


In [ ]:
evals , evecs = la.eig(S)
print(evals)
print(evecs)

[482.65184313+0.j  50.89133245+0.j   6.9380102 +0.j  23.51881422+0.j]
[[ 0.44086301  0.59384165  0.66845617  0.07847454]
 [ 0.42756559 -0.79704499  0.41409794  0.10212658]
 [ 0.60406253  0.04743761 -0.35708136 -0.71088047]
 [ 0.50787393  0.0991012  -0.50416481  0.69141946]]


In [ ]:
v1 = evecs[:,0]
print(v1)
v2 = evecs[:,1]
print(v2)

[0.44086301 0.42756559 0.60406253 0.50787393]
[ 0.59384165 -0.79704499  0.04743761  0.0991012 ]


In [ ]:
v1 @ v2

-2.636779683484747e-16

In [ ]:
D = np.diag((3,2,1,4))
print(D)

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 4]]


In [ ]:
M = P @ D @ la.inv(P)
evals1 , evecs1 = la.eig(M)
print(evals1)
print(evecs1)

[4.+0.j 1.+0.j 3.+0.j 2.+0.j]
[[-0.66436384  0.3617873   0.09534626  0.46028731]
 [-0.08304548  0.65121714  0.57207755  0.18411492]
 [-0.66436384  0.43414476  0.76277007  0.46028731]
 [-0.33218192  0.50650222  0.28603878  0.73645969]]


In [ ]:
Pinv = la.inv(P)
k=20

In [ ]:
%%timeit
result = M.copy()
for _ in range(1,k):
  result = result + M

The slowest run took 144.37 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 13.3 µs per loop


In [ ]:
%%timeit
P @ D**k @ Pinv

The slowest run took 18.84 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.3 µs per loop
